/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as FreelanceRouteImport } from './routes/freelance'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as FreelanceIdRouteImport } from './routes/freelance.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceRoute = FreelanceRouteImport.update({
  id: '/freelance',
  path: '/freelance',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceIdRoute = FreelanceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FreelanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresa': typeof EmpresaRoute
  '/freelance': typeof FreelanceRouteWithChildren
  '/painel': typeof PainelRoute
  '/freelance/$id': typeof FreelanceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresa': typeof EmpresaRoute
  '/freelance': typeof FreelanceRouteWithChildren
  '/painel': typeof PainelRoute
  '/freelance/$id': typeof FreelanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresa': typeof EmpresaRoute
  '/freelance': typeof FreelanceRouteWithChildren
  '/painel': typeof PainelRoute
  '/freelance/$id': typeof FreelanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empresa' | '/freelance' | '/painel' | '/freelance/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empresa' | '/freelance' | '/painel' | '/freelance/$id'
  id:
    '__root__' | '/' | '/empresa' | '/freelance' | '/painel' | '/freelance/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresaRoute: typeof EmpresaRoute
  FreelanceRoute: typeof FreelanceRouteWithChildren
  PainelRoute: typeof PainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance': {
      id: '/freelance'
      path: '/freelance'
      fullPath: '/freelance'
      preLoaderRoute: typeof FreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/$id': {
      id: '/freelance/$id'
      path: '/$id'
      fullPath: '/freelance/$id'
      preLoaderRoute: typeof FreelanceIdRouteImport
      parentRoute: typeof FreelanceRoute
    }
  }
}

interface FreelanceRouteChildren {
  FreelanceIdRoute: typeof FreelanceIdRoute
}

const FreelanceRouteChildren: FreelanceRouteChildren = {
  FreelanceIdRoute: FreelanceIdRoute,
}

const FreelanceRouteWithChildren = FreelanceRoute._addFileChildren(
  FreelanceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresaRoute: EmpresaRoute,
  FreelanceRoute: FreelanceRouteWithChildren,
  PainelRoute: PainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
