/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as FreelanceIndexRouteImport } from './routes/freelance.index'
import { Route as FreelanceIdRouteImport } from './routes/freelance.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceIndexRoute = FreelanceIndexRouteImport.update({
  id: '/freelance/',
  path: '/freelance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceIdRoute = FreelanceIdRouteImport.update({
  id: '/freelance/$id',
  path: '/freelance/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresa': typeof EmpresaRoute
  '/painel': typeof PainelRoute
  '/freelance/$id': typeof FreelanceIdRoute
  '/freelance/': typeof FreelanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresa': typeof EmpresaRoute
  '/painel': typeof PainelRoute
  '/freelance/$id': typeof FreelanceIdRoute
  '/freelance': typeof FreelanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/empresa': typeof EmpresaRoute
  '/painel': typeof PainelRoute
  '/freelance/$id': typeof FreelanceIdRoute
  '/freelance/': typeof FreelanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/empresa' | '/painel' | '/freelance/$id' | '/freelance/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/empresa' | '/painel' | '/freelance/$id' | '/freelance'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/empresa'
    | '/painel'
    | '/freelance/$id'
    | '/freelance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EmpresaRoute: typeof EmpresaRoute
  PainelRoute: typeof PainelRoute
  FreelanceIdRoute: typeof FreelanceIdRoute
  FreelanceIndexRoute: typeof FreelanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/': {
      id: '/freelance/'
      path: '/freelance'
      fullPath: '/freelance/'
      preLoaderRoute: typeof FreelanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/$id': {
      id: '/freelance/$id'
      path: '/freelance/$id'
      fullPath: '/freelance/$id'
      preLoaderRoute: typeof FreelanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EmpresaRoute: EmpresaRoute,
  PainelRoute: PainelRoute,
  FreelanceIdRoute: FreelanceIdRoute,
  FreelanceIndexRoute: FreelanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
