// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbwbpyknqbaeytnbqtkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhid2JweWtucWJhZXl0bmJxdGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYyOTU5NjksImV4cCI6MjEwMTg3MTk2OX0.ogmTPO64O-Mq_dbdlebFKRsyF6v9K3_YhpSeZe9tpV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});